[package]
name = "cinematic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "CineMatic is a powerful and user-friendly Discord bot that allows users to manage their media collections. With its advanced features, Cinematic can help you make changes to your media server, view available content, and even answer questions related to your media collection."
repository = "https://github.com/CodedNil/CineMatic"
keywords = ["discord", "media-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-openai = "0.14.0"
chrono = "0.4"
futures = "0.3"
rand = "0.8"
regex = "1.8"
reqwest = "0.11"
scraper = "0.17"
serde = "1.0"
serde_json = "1.0"
serenity = { version = "0.11", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
tiktoken-rs = "0.5"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
toml = "0.7"
